# Generated by Django 6.0.3 on 2026-03-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_or_volunteered_before', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('hopecare_employment_details', models.TextField(blank=True, help_text='Please provide details about your previous employment or volunteer work', verbose_name='If yes, please specify where, when, and your position or role')),
                ('how_did_you_hear', models.CharField(help_text='e.g., Website, Social Media, Friend, Newspaper, etc.', max_length=255, verbose_name='How did you hear about the volunteer program at Hopecare Center?')),
                ('reasons_for_volunteering', models.TextField(help_text='Tell us what motivates you to volunteer with Hopecare', verbose_name='Describe your main reasons for wanting to volunteer')),
                ('volunteer_interest', models.CharField(choices=[('teaching', 'Teaching/Tutoring'), ('mentoring', 'Mentoring'), ('caregiving', 'Child Caregiving'), ('admin', 'Administrative Work'), ('events', 'Event Planning'), ('fundraising', 'Fundraising'), ('outreach', 'Community Outreach'), ('technical', 'Technical/IT Support'), ('other', 'Other')], max_length=50, verbose_name='Type of volunteer work that interests you')),
                ('volunteer_interest_other', models.CharField(blank=True, max_length=255, verbose_name='If Other, please specify')),
                ('availability', models.CharField(choices=[('weekdays_morning', 'Weekday Mornings'), ('weekdays_afternoon', 'Weekday Afternoons'), ('weekdays_evening', 'Weekday Evenings'), ('weekends_morning', 'Weekend Mornings'), ('weekends_afternoon', 'Weekend Afternoons'), ('weekends_evening', 'Weekend Evenings'), ('flexible', 'Flexible/As Needed')], max_length=50, verbose_name='What is your availability?')),
                ('availability_details', models.TextField(blank=True, help_text='Please provide any additional information about your schedule', verbose_name='Additional availability details')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=20, verbose_name='Are you currently employed?')),
                ('employment_details', models.TextField(blank=True, help_text='Please provide your employer name and job title if employed', verbose_name='Employment details')),
                ('special_skills', models.TextField(help_text='List any relevant skills, certifications, training, or experience', verbose_name='Special skills, training or qualifications you would like to use in your volunteer role')),
                ('certification', models.BooleanField(default=False, verbose_name='I certify that the information in this application is correct and complete to the best of my knowledge.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
