# Generated by Django 6.0.3 on 2026-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Please provide a contact phone number', max_length=20, verbose_name='Phone Number'),
        ),
    ]
