# Generated by Django 6.0.3 on 2026-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role/Position')),
                ('bio', models.TextField(help_text='Short bio shown on team page', verbose_name='Bio/Description')),
                ('photo', models.ImageField(help_text='Upload team member photo (recommended: 400x400px, square crop)', upload_to='team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
